/* XPM */
static char * defaulticon[] = {
"50 50 9 1",
" 	s None	c None",
".	c gray70",
"X	c #d26d9a",
"+	c #b24d7a",
"o	c #922d5a",
"O	c white",
"@	c red",
"#	c gray30",
"$	c gray55",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
" @@@@@@@@@@                @@@                    ",
"  @@@@@@@@@@              @@@                     ",
"   @@@@@@@@@@            @@@                      ",
"    @@@@@@@@@@          @@@                       ",
"     @@@@@@@@@@        @@@                        ",
"      @@@@@@@@@@      @@@                         ",
"       @@@@@@@@@@    @@@                          ",
"        @@@@@@@@@@  @@@                           ",
"         @@@@@@@@@ @@@                            ",
"          @@@@@@@ @@@                             ",
"           @@@@@ @@@@                             ",
"            @@@ @@@@@@                            ",
"   ########@@@#@@@@@@@@########################   ",
"   #......@@@.@@@@@@@@@@.......................   ",
"   #.XXXX@@@XXX@@@@@@@@@@XXXXXXXXXXXXXXXXXXXX#.   ",
"   #.X++@@@+++++@@@@@@@@@@+++++++++++++++++Xo#.   ",
"   #.X+@@@+++++++@@@@@@@@@@++++++++++++++++Xo#.   ",
"   #.X@@@+++++++++@@@@@@@@@@+++++++++++++++Xo#.   ",
"   #.@@@+++++++++++@@@@@@@@@@++++++++++++++Xo#.   ",
"   #@@@ooooooooooooo@@@@@@@@@@oooooooooooooXo#.   ",
"   @@@oOOOOOOOOOOOOOO@@@@@@@@@@OOOOOOOOOOOOXo#.   ",
"  @@@XoO#####OOOOOOOOO@@@@@@@@@@OOOOOOOOOOOXo#.   ",
" @@@.XoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXo#.   ",
"   #.XoO###OO###OOOOOOOOOOOOOOOOOOOOOOOOOOOXo#.   ",
"   #.XoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXo#.   ",
"   #.XoO####OO###OOOOOOOOOOOOOOOOOOOOOOOOOOXo#.   ",
"   #.XoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXo#.   ",
"   #.XoO###OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXo#.   ",
"   #.XoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXo#.   ",
"   #.XoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXo#.   ",
"   #.XoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXo#.   ",
"   #.XoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXo#.   ",
"   #.XoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXo#.   ",
"   #.XoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXo#.   ",
"   #.XoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXo#.   ",
"   #.XoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXo#.   ",
"   #.XoXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo#.   ",
"   #.Xooooooooooooooooooooooooooooooooooooooo#.   ",
"   #.#########################################.   ",
"   #...........................................   ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  "};
